### ISSUE TITLE
ldap admin password change

### ISSUE THREAD

**Issue by fvanderbiest** [landryb/georchestra-ansible#18]
I tried to customize the ldap admin password in https://github.com/landryb/georchestra-ansible/blob/master/playbooks/georchestra.yml#L9 but this resulted in a failure to create the user.
(sorry, no logs for now ...)

**Comment by landryb** [comment]
Probably because the admin pw is not synced/templated there:
https://github.com/georchestra/LDAP/blob/master/georchestra-bootstrap.ldif#L8

**Comment by landryb** [comment]
openldap_rootdn should probably also templated

**Comment by landryb** [comment]
Should be fixed now that all openldap variables are properly replaced/templated when populating the DIT.
